#!/usr/bin/env python3
"""生成知言的颜色令牌：res/values/tokens.xml（浅色）与 res/values-night/tokens.xml（深色）。

颜色不手调。种子色经 Material Color Utilities 的 HCT 算法（2025 版规范，Tonal Spot 变体，
即 Android 16 与 M3 Expressive 的默认方案）推出全部系统角色。

M3 只有 error 一种语义色；知言的状态还要「成功」「警告」。这两支按 M3 自定义色的做法：
先向种子色相 harmonize，再用同一套 Tonal Spot 规则取 primary / on-primary /
primary-container / on-primary-container 四个角色，明度结构与主色完全同构，
对比度由算法保证、再由 tests/DesignTokenTest 按 WCAG 2.2 钉住。

依赖：pip install materialyoucolor
运行：python3 tools/make-tokens.py [--check]
"""

import sys
from pathlib import Path

from materialyoucolor.blend import Blend
from materialyoucolor.dynamiccolor.material_dynamic_colors import MaterialDynamicColors as M
from materialyoucolor.hct.hct import Hct
from materialyoucolor.scheme.scheme_tonal_spot import SchemeTonalSpot

ROOT = Path(__file__).resolve().parent.parent
LIGHT = ROOT / "res/values/tokens.xml"
DARK = ROOT / "res/values-night/tokens.xml"

# 种子：青（#00838F）。知言是「微信的话」，取介于蓝绿之间的青——与微信的绿有呼应，
# 又与成功色（绿）拉开色相，状态卡片的「就绪」不会和品牌色混成一片。
SEED = 0xFF00838F
SUCCESS = 0xFF2E8B57
WARNING = 0xFFB8860B

# (资源名, MaterialDynamicColors 角色, 注释)
ROLES = [
    ("primary", "primary", "主色：品牌与每屏唯一的主操作"),
    ("on_primary", "onPrimary", None),
    ("primary_container", "primaryContainer", None),
    ("on_primary_container", "onPrimaryContainer", None),
    ("inverse_primary", "inversePrimary", None),
    ("secondary", "secondary", "次色：选中态与色调按钮"),
    ("on_secondary", "onSecondary", None),
    ("secondary_container", "secondaryContainer", None),
    ("on_secondary_container", "onSecondaryContainer", None),
    ("tertiary", "tertiary", "第三色：与主色有别的强调（群聊标记）"),
    ("on_tertiary", "onTertiary", None),
    ("tertiary_container", "tertiaryContainer", None),
    ("on_tertiary_container", "onTertiaryContainer", None),
    ("error", "error", "错误：破坏性操作与失败态"),
    ("on_error", "onError", None),
    ("error_container", "errorContainer", None),
    ("on_error_container", "onErrorContainer", None),
    ("surface", "surface", "表面：靠明度分层，不靠阴影"),
    ("surface_container_lowest", "surfaceContainerLowest", None),
    ("surface_container_low", "surfaceContainerLow", None),
    ("surface_container", "surfaceContainer", None),
    ("surface_container_high", "surfaceContainerHigh", None),
    ("surface_container_highest", "surfaceContainerHighest", None),
    ("on_surface", "onSurface", None),
    ("on_surface_variant", "onSurfaceVariant", None),
    ("inverse_surface", "inverseSurface", None),
    ("inverse_on_surface", "inverseOnSurface", None),
    ("outline", "outline", "轮廓：outline 承担必须被看见的边界（≥ 3:1）；outline_variant 只作装饰"),
    ("outline_variant", "outlineVariant", None),
    ("scrim", "scrim", None),
]
CUSTOM = [("success", SUCCESS, "成功：服务就绪"), ("warning", WARNING, "警告：等待登录、待生效、被拦下")]


def hexs(argb: int) -> str:
    return "#%06X" % (argb & 0xFFFFFF)


def scheme(source: int, dark: bool):
    return SchemeTonalSpot(Hct.from_int(source), dark, 0.0, spec_version="2025")


def document(dark: bool) -> str:
    base = scheme(SEED, dark)
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!--",
        f"  知言 Design Tokens · 颜色（{'深' if dark else '浅'}色）",
        "  @generated by tools/make-tokens.py —— 不要手改；改种子色后重新运行。",
        f"  seed {hexs(SEED)} · Tonal Spot · spec 2025；success / warning 为 harmonize 后的自定义色。",
        "  界面代码只经 R 按语义角色取色（tests/DesignTokenTest 拦截字面色值），对比度由同一测试按 WCAG 2.2 AA 钉住。",
        "-->",
        "<resources>",
    ]
    for name, role, note in ROLES:
        if note:
            lines.append(f"    <!-- {note} -->")
        lines.append(f'    <color name="md_{name}">{hexs(getattr(M, role).get_argb(base))}</color>')
    for name, raw, note in CUSTOM:
        custom = scheme(Blend.harmonize(raw, SEED), dark)
        lines.append(f"    <!-- {note} -->")
        for suffix, role in (("", "primary"), ("on_", "onPrimary")):
            lines.append(f'    <color name="md_{suffix}{name}">{hexs(getattr(M, role).get_argb(custom))}</color>')
        for suffix, role in (("", "primaryContainer"), ("on_", "onPrimaryContainer")):
            lines.append(f'    <color name="md_{suffix}{name}_container">{hexs(getattr(M, role).get_argb(custom))}</color>')
    on_surface = getattr(M, "onSurface").get_argb(base)
    lines.append("    <!-- 状态层：on_surface 10%，供系统控件（文本选择手柄、默认波纹）使用 -->")
    lines.append(f'    <color name="md_state_layer">#1A{hexs(on_surface)[1:]}</color>')
    lines.append("</resources>")
    return "\n".join(lines) + "\n"


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for path, dark in ((LIGHT, False), (DARK, True)):
        text = document(dark)
        if path.exists() and path.read_text() == text:
            continue
        stale.append(path.relative_to(ROOT))
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    if check and stale:
        print("过期：" + "、".join(map(str, stale)) + "；运行 python3 tools/make-tokens.py")
        return 1
    print("颜色令牌与种子一致。" if not stale else "已生成：" + "、".join(map(str, stale)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
