#!/usr/bin/env python3
"""图标：Material Symbols Rounded 官方矢量 → VectorDrawable；应用图标 SVG → 自适应图标图层。

界面图标一律取 Google 官方的 Material Symbols Rounded（Apache-2.0，权重 400、等级 0、
光学尺寸 24），不手画：M3E 的图标体系就是它。SVG 原稿存在 artwork/symbols/，
缺了才去 fonts.gstatic.com 下载一次，之后离线可重复生成。

输出（均为生成物，不要手改）：
  res/drawable/ms_<name>.xml             界面图标，颜色由代码按令牌着色
  res/drawable/ic_launcher_*.xml         自适应图标的背景 / 前景 / 单色层

运行：python3 tools/make-icons.py [--check]
"""

import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SYMBOLS = ROOT / "artwork/symbols"
DRAWABLE = ROOT / "res/drawable"
SVG = "{http://www.w3.org/2000/svg}"
URL = "https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsrounded/{name}/{style}/24px.svg"

# 资源名 → (符号名, 样式)。样式 default = 描边（未选中/常态），fill1 = 实心（选中/强调）。
ICONS = {
    "refresh": ("refresh", "default"),
    "settings": ("settings", "default"),
    "arrow_back": ("arrow_back", "default"),
    "close": ("close", "default"),
    "content_copy": ("content_copy", "default"),
    "share": ("share", "default"),
    "check": ("check", "default"),
    "check_circle": ("check_circle", "fill1"),
    "schedule": ("schedule", "fill1"),
    "error": ("error", "fill1"),
    "warning": ("warning", "fill1"),
    "info": ("info", "fill1"),
    "pending": ("pending", "fill1"),
    "visibility": ("visibility", "default"),
    "visibility_off": ("visibility_off", "default"),
    "key": ("key", "default"),
    "chevron_right": ("chevron_right", "default"),
    "open_in_new": ("open_in_new", "default"),
    "restart_alt": ("restart_alt", "default"),
    "add": ("add", "default"),
    "search": ("search", "default"),
    "person": ("person", "default"),
    "group": ("group", "default"),
    "edit": ("edit", "default"),
    "link": ("link", "default"),
    "block": ("block", "default"),
    "folder": ("folder", "default"),
}
MIRRORED = {"arrow_back", "chevron_right", "open_in_new"}

HEADER = "<!-- @generated by tools/make-icons.py from {source}; do not edit. -->\n"


def fetch(name: str, style: str) -> Path:
    path = SYMBOLS / f"{name}{'' if style == 'default' else '_' + style}.svg"
    if not path.exists():
        with urllib.request.urlopen(URL.format(name=name, style=style), timeout=20) as response:
            data = response.read()
        if b"<svg" not in data:
            raise RuntimeError(f"{name}/{style}: not an SVG")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    return path


def symbol_vector(key: str, source: Path) -> str:
    root = ET.parse(source).getroot()
    x, y, w, h = (float(v) for v in root.attrib["viewBox"].split())
    paths = [p.attrib["d"] for p in root.iter(SVG + "path")]
    if not paths:
        raise RuntimeError(f"{source.name}: no path")
    mirrored = ' android:autoMirrored="true"' if key in MIRRORED else ""
    body = "\n".join(f'        <path android:fillColor="#FF000000" android:pathData="{d}" />' for d in paths)
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        + HEADER.format(source=f"artwork/symbols/{source.name}")
        + '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="24dp" android:height="24dp"\n'
        f'    android:viewportWidth="{w:g}" android:viewportHeight="{h:g}"{mirrored}>\n'
        f'    <group android:translateX="{-x:g}" android:translateY="{-y:g}">\n'
        f"{body}\n"
        "    </group>\n"
        "</vector>\n"
    )


def launcher_layer(paths, source: str) -> str:
    out = [
        '<?xml version="1.0" encoding="utf-8"?>',
        HEADER.format(source=source).rstrip(),
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">',
    ]
    for p in paths:
        attrs = [f'android:pathData="{p.attrib["d"]}"']
        fill = p.get("fill", "#000000")
        if fill != "none":
            attrs.append(f'android:fillColor="{fill}"')
            if p.get("fill-rule") == "evenodd":
                attrs.append('android:fillType="evenOdd"')
        stroke = p.get("stroke")
        if stroke:
            attrs.append(f'android:strokeColor="{stroke}"')
            attrs.append(f'android:strokeWidth="{p.get("stroke-width", "1")}"')
            for svg_name, android_name in (("stroke-linecap", "strokeLineCap"), ("stroke-linejoin", "strokeLineJoin")):
                if p.get(svg_name):
                    attrs.append(f'android:{android_name}="{p.get(svg_name)}"')
        out.append("    <path " + " ".join(attrs) + " />")
    out.append("</vector>")
    return "\n".join(out) + "\n"


def launcher() -> dict:
    icon = ET.parse(ROOT / "artwork/icon.svg").getroot()
    layers = {g.attrib["id"]: [p for p in g if p.tag == SVG + "path"] for g in icon.iter(SVG + "g") if "id" in g.attrib}
    mono = [p for p in ET.parse(ROOT / "artwork/icon-monochrome.svg").getroot().iter(SVG + "path")]
    return {
        DRAWABLE / "ic_launcher_background.xml": launcher_layer(layers["background"], "artwork/icon.svg"),
        DRAWABLE / "ic_launcher_foreground.xml": launcher_layer(layers["foreground"], "artwork/icon.svg"),
        DRAWABLE / "ic_launcher_monochrome.xml": launcher_layer(mono, "artwork/icon-monochrome.svg"),
    }


def main() -> int:
    check = "--check" in sys.argv
    outputs = {DRAWABLE / f"ms_{key}.xml": symbol_vector(key, fetch(*spec)) for key, spec in ICONS.items()}
    outputs.update(launcher())
    stale = [path for path, text in outputs.items() if not path.exists() or path.read_text() != text]
    # 不再使用的生成物一并清掉，避免资源里残留孤儿图标。
    orphans = [p for p in DRAWABLE.glob("ms_*.xml") if p not in outputs]
    if check:
        if stale or orphans:
            print("过期：" + "、".join(p.name for p in stale + orphans) + "；运行 python3 tools/make-icons.py")
            return 1
        print("图标与原稿一致。")
        return 0
    for path in stale:
        path.write_text(outputs[path])
    for path in orphans:
        path.unlink()
    print(f"图标：{len(outputs)} 个，更新 {len(stale)} 个，清理 {len(orphans)} 个。")
    return 0


if __name__ == "__main__":
    sys.exit(main())
